import React from 'react'
import img from '../../../../../../assets/bio/Bio9th/Picture1.png'
import img2 from '../../../../../../assets/bio/Bio9th/Picture2.png'

const BioTheory92 = () => {
  return (
    <div className='w-4/5 pl-4'>
      <div className="aim mt-8 mb-3">
        <p className="text-dark font-semibold text-xl mb-1">Cell/Cell Organelles</p>
        <p className="text-dark50 font-normal text-base pl-3">The structural and functional unit of life is the cell. The study of the structure and functioning of cells is known as cell biology. It is concerned with life processes, signalling pathways, physiological qualities, metabolic properties, chemical properties, and cell-environment interactions.
          <br /><br />
          The inside of any animal or plant cell has numerous comparable room-like structures called organelles, which are analogous to the rooms in our homes. Here are some names and explanations of organelles and other cell components.</p>

        <img src={img} alt="" className='my-5' />


        <p className="text-dark font-semibold text-xl mb-1">Cell Wall: Protective Coat in Plant Cells</p>
        <p className="text-dark50 font-normal text-base pl-3">The presence of a cell wall, which is present solely in plant cells and surrounds the cell membrane, is the most fundamental distinction between plant and animal cells.The cell wall is made of cellulose fibre, polysaccharides, and proteins and is hard. Despite the cell wall's stiffness, chemical messages and cellular excretions can travel across cells.</p>


        <p className="text-dark font-semibold text-xl mb-1">Cell Membrane: Protective Coat in Animal Cells</p>
        <p className="text-dark50 font-normal text-base pl-3">The cell membrane is found in both plants and animals, and it is the outermost layer that separates the contents of the cell from the outside world in the animal cell. It is made up of both lipids and proteins and is selectively permeable, which means that only certain molecules may flow through it.</p>



        <p className="text-dark font-semibold text-xl mb-1">Cytoplasm: Cell’s Inner Space</p>
        <p className="text-dark50 font-normal text-base pl-3">Cytoplasm is an eighty percent water jelly-like material that is usually transparent in colour. It is also known as cytosol. All of the organelles found within the cell membrane are found in the cytoplasm. The cytosol stores dissolved nutrients, aids in waste breakdown, and transports material around the cell via a process known as cytoplasmic streaming.</p>



        <p className="text-dark font-semibold text-xl mb-1">Nucleus: The Control Centre</p>
        <p className="text-dark50 font-normal text-base pl-3">The nucleus is recognised as the cell's command and control core.It contains the regulatory machinery that controls all of the cell's operations. It is the cell's biggest organelle and houses the DNA. DNA includes all of the information necessary for cells to exist, function, and replicate.The nucleus is protected by a double-layered covering known as the nuclear membrane.</p>



        <p className="text-dark font-semibold text-xl mb-1">Vacuoles: Cell’s Storage Space</p>
        <p className="text-dark50 font-normal text-base pl-3">A vacuole is a membrane-bound organelle that retains solid and liquid substances. Vacuoles can be found in both animal and plant cells, but they are much larger in plant cells. Vacuoles are generated by the fusing of several membrane vesicles and are essentially just bigger versions of these. The organelle has no fixed shape or size; its structure changes depending on the needs of the cell.</p>

        <p className="text-dark font-semibold text-xl mb-1">Similarities and Differences between Plant and Animal Cells</p>
        <p className="text-dark50 font-normal text-base pl-3">Animal and plant cells have many similarities, yet there are also some notable distinctions. Here are some of the differences and similarities between plant and animal cells</p>

        <img src={img2} alt="" className="pb-10" />

      </div>
    </div>
  )
}

export default BioTheory92